kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: review-proposal-facts
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  keyExtras: [name]

  widgetData:
    title: Proposal
    titleVariant: eyebrow
    variant: outlined
    size: small
    items:
    - resourceRefId: review-proposal-facts-list

  resourcesRefs:
    items:
    - id: review-proposal-facts-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: review-proposal-facts-list
      namespace: {{ .Release.Namespace }}
      resource: descriptions
      verb: GET
