{{/* "Manifest" card wrapping the object's YAML view. */}}
kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: card-resource-detail-manifest
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  keyExtras: [namespace, group, version, plural, name]
  widgetData:
    title: Manifest
    titleVariant: eyebrow
    variant: outlined
    items:
    - resourceRefId: resource-detail-manifest
  resourcesRefs:
    items:
    - id: resource-detail-manifest
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: resource-detail-manifest
      namespace: {{ .Release.Namespace }}
      resource: yamlviewers
      verb: GET
