{{- if (.Values.observability | default dict).snowplowSli }}
kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sp-card-build-version
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    title: Running build
    titleVariant: eyebrow
    variant: outlined
    allowedResources:
    - statistics
    items:
    - resourceRefId: sp-build-version
  resourcesRefs:
    items:
      - id: sp-build-version
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: sp-build-version
        namespace: {{ .Release.Namespace }}
        resource: statistics
        verb: GET
{{- end }}
