{{- if (.Values.observability | default dict).snowplowSli }}
kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sp-card-cache-size
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    title: Resolved-cache occupancy
    titleVariant: eyebrow
    variant: outlined
    allowedResources:
    - linecharts
    items:
    - resourceRefId: sp-cache-size
  resourcesRefs:
    items:
      - id: sp-cache-size
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: sp-cache-size
        namespace: {{ .Release.Namespace }}
        resource: linecharts
        verb: GET
{{- end }}
