kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: review-proposal-why
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  keyExtras: [name]

  widgetData:
    title: Why
    titleVariant: eyebrow
    variant: outlined
    size: small
    items:
    - resourceRefId: review-proposal-rationale

  resourcesRefs:
    items:
    - id: review-proposal-rationale
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: review-proposal-rationale
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
