kind: Flex
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: review-reject
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  keyExtras: [name]
  widgetData:
    vertical: true
    gap: middle
    allowedResources:
    - paragraphs
    - forms
    items:
    - resourceRefId: review-reject-intro
    - resourceRefId: review-reject-form
  resourcesRefs:
    items:
    - id: review-reject-intro
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: review-reject-intro
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
    - id: review-reject-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: review-reject-form
      namespace: {{ .Release.Namespace }}
      resource: forms
      verb: GET
