# Observability section header — obs-sec-components-label
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: obs-sec-components-label
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    text: 'Components'
    strong: true
  resourcesRefs:
    items: []
