{{/* Observability section header — obs-sec-reconciliation-label */}}
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: obs-sec-reconciliation-label
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    text: 'Reconciliation'
    strong: true
  resourcesRefs:
    items: []
