{{- if (.Values.observability | default dict).snowplowSli }}
kind: Statistic
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sp-pod-uptime
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
    "krateo.io/external-cache-ttl-seconds": "30"
spec:
  keyExtras: [range]
  apiRef:
    name: sp-pod-uptime
    namespace: {{ .Release.Namespace }}
  widgetData:
    title: Pod uptime (min)
    value: 0
  widgetDataTemplate:
  - forPath: value
    expression: '${ ([ (.rows // [])[] | (.uptime_min|tonumber) ] | first // 0) }'
  resourcesRefs:
    items: []
{{- end }}
